
import React, { useId } from 'react';

interface MotlatsiLogoProps {
  className?: string;
  variant?: 'full' | 'icon';
}

const MotlatsiLogo: React.FC<MotlatsiLogoProps> = ({ className, variant = 'full' }) => {
  const id = useId();
  // Ensure ID is valid for SVG url reference by removing colons generated by React's useId
  const gradientId = `motlatsi-grad-${id.replace(/:/g, '')}`;

  return (
    <svg 
      viewBox={variant === 'icon' ? "0 0 50 50" : "0 0 220 50"} 
      xmlns="http://www.w3.org/2000/svg" 
      className={className}
      aria-label="Motlatsi AI Logo"
    >
      <defs>
        <linearGradient id={gradientId} x1="0" y1="0" x2="1" y2="1">
          <stop offset="0%" stopColor="#2AF598"/>
          <stop offset="100%" stopColor="#009EFD"/>
        </linearGradient>
      </defs>

      {/* Icon Part - Centered in 50x50 area */}
      <g>
         {/* Bracket Shape: Top-Left-Bottom open box */}
         <path 
            d="M 35 12 H 12 V 38 H 35" 
            fill="none" 
            stroke={`url(#${gradientId})`}
            strokeWidth="3" 
            strokeLinecap="round" 
            strokeLinejoin="round"
         />
         {/* Letter M inside */}
         <text 
            x="23.5" 
            y="32" 
            textAnchor="middle" 
            fontFamily="'Lexend', sans-serif" 
            fontWeight="400" 
            fontSize="18" 
            fill={`url(#${gradientId})`}
         >M</text>
      </g>

      {/* Text Part - Only for full variant */}
      {variant === 'full' && (
        <text 
            x="55" 
            y="33" 
            fontFamily="'Lexend', sans-serif" 
            fontWeight="500" 
            fontSize="22" 
            letterSpacing="3" 
            fill={`url(#${gradientId})`}
        >
            MOTLATSI
        </text>
      )}
    </svg>
  );
};

export default MotlatsiLogo;
