
export type UserRole = 'admin' | 'teacher' | 'student' | 'parent';

export interface Subject {
  id: string;
  name: string;
  grade: string;
  topics: Topic[];
}

export interface UserState {
  id: string;
  name: string;
  role: UserRole;
  email?: string;
  school?: string;
  schoolId?: string;
  organization_id?: string;
  isDemo?: boolean;
  ai_credits?: number;
  completedTopics: string[];
  currentGrade?: string;
  linkedStudentIds?: string[];
  learningNeeds?: LearningNeed[];
  subject?: string;
  teachingSubjects?: TeachingAssignment[];
  masteredObjectives?: { [topicId: string]: string[] };
  parentLinkCode?: string;
  status?: string;
}

export interface CacheEntry<T> {
  data: T;
  timestamp: number;
  version: number;
}

export interface Topic {
  id: string;
  title: string;
  description: string;
  grade: string;
  subject: string;
  learningObjectives?: string[];
  keyVocabulary?: { term: string; definition: string; }[];
  prerequisiteTopicIds?: string[];
  curriculumStandards?: string[];
}

export interface Grade {
  grade: string;
  subjects: {
    name: string;
    topics: Topic[];
  }[];
}

export interface QuizQuestion {
  id: string;
  question: string;
  options: string[];
  correctAnswer: number;
  explanation?: string;
}

export interface ScheduleSlot {
  id: string;
  day: string;
  date?: string;
  time: string;
  subject: string;
  grade?: string;
  type: 'class' | 'study' | 'exam' | 'remedial';
  notes?: string;
  location?: string;
  autoGenerated?: boolean;
  linkedTopicId?: string;
  linkedResourceId?: string;
  status?: 'planned' | 'completed' | 'missed' | 'done' | 'today' | 'upcoming';
}

export interface SavedItem {
  id: string;
  type: 'lesson' | 'worksheet' | 'quiz' | 'note' | 'flashcard';
  title: string;
  date: string;
  data: any;
}

export interface GradeRecord {
  id: string;
  studentId: string;
  studentName?: string;
  itemId?: string;
  itemTitle: string;
  score: number;
  total: number;
  date: string;
  type: 'quiz' | 'battle' | 'assignment';
  topicId?: string;
  teacherReviewed?: boolean;
}

export interface AccessibilitySettings {
  dyslexicFont: boolean;
  highContrast: boolean;
  simplifiedLanguage: boolean;
  autoTranscript: boolean;
  dataSaver: boolean;
}

export interface TermConfig {
  id: string;
  name: string;
  startDate: string;
  endDate: string;
  isActive: boolean;
}

export interface StudyConstraints {
  preferredDays: string[];
  maxHoursPerDay: number;
  focusSubjects: string[];
  schoolStart?: string;
  schoolEnd?: string;
  preferredStudyStart?: string;
  preferredStudyEnd?: string;
  breakTime?: string;
  lunchTime?: string;
  masterSchedule?: any;
  studyDays?: string[];
}

export type TopicStatus = 'not-started' | 'in-progress' | 'mastered' | 'remedial-needed' | 'locked' | 'ready';

export interface ChatMessage {
  id: number;
  sender: 'user' | 'ai';
  text: string;
  timestamp: number;
}

export interface TeachingAssignment {
  grades: string[];
  subject: string;
}

export type LearningNeed = 'visual_impairment' | 'auditory_impairment' | 'dyslexia' | 'adhd' | 'motor_impairment' | 'autism_spectrum';

export interface StudentNotification {
  id: string;
  studentId?: string;
  title: string;
  message: string;
  date: string;
  read: boolean;
  type: 'info' | 'success' | 'warning' | 'error' | 'system' | 'alert';
}

export interface Curriculum {
  primary: {
    grade: string;
    subjects: {
      name: string;
      topics: Topic[];
    }[];
  }[];
  highSchool: {
    grade: string;
    subjects: {
      name: string;
      topics: Topic[];
    }[];
  }[];
}

export interface SavedResource {
  id: string;
  title: string;
  type: string;
  url?: string;
  content?: string;
  date: string;
  subject?: string;
  grade?: string;
}

export type StudyMode = 'intro' | 'exam-prep' | 'deep-dive';

export type AppView = 
  | 'dashboard' 
  | 'admin' 
  | 'admin-users' 
  | 'admin-curriculum' 
  | 'scheduler' 
  | 'wizard' 
  | 'classroom' 
  | 'library' 
  | 'profile' 
  | 'accessibility' 
  | 'student-hub' 
  | 'student-voice' 
  | 'student-library' 
  | 'battle' 
  | 'choice-hub' 
  | 'interactive-lesson' 
  | 'audio-lesson' 
  | 'inclusive-quiz' 
  | 'flashcards' 
  | 'chalkboard' 
  | 'chat' 
  | 'quiz' 
  | 'worksheet-generator'
  | 'revision-notes'
  | 'arcade-dashboard'
  | 'ludo-battle'
  | 'knowledge-maze'
  | 'flashcard-arcade'
  | 'morabaraba-battle'
  | 'memory-battle'
  | 'lingo-battle'
  | 'bulk-planner-dashboard'
  | 'bulk-unit-creator'
  | 'bulk-reporter'
  | 'journey';
